
trigger: none

pool: default

stages:
  - stage: stage1
    displayName: stage1
    jobs:
      - job: job1
        displayName: terraforminstall
        steps:
        - task: TerraformInstaller@1
          inputs:
            terraformVersion: 'latest'
      - job: job2
        displayName: terraforminit
        steps:
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/env/dev'
            backendServiceArm: 'myserviceconnection'
            backendAzureRmStorageAccountName: 'devstg4'
            backendAzureRmContainerName: 'devcontainer'
            backendAzureRmKey: 'ahmad.tfstate'

  - stage: stage2
    displayName: stage2
    jobs:
      - job: securityscan
        displayName: security scan with tflint
        steps:
        - task: PowerShell@2
          inputs:
            targetType: 'inline'
            script: |
              tflint --init
              tflint
            workingDirectory: '$(System.DefaultWorkingDirectory)'





